/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pocket.hospital;

/**
 *
 * @author aahir
 */
public class Loading extends javax.swing.JFrame {

    /**
     * Creates new form Loading
     */
    public Loading() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        head = new javax.swing.JLabel();
        subhead = new javax.swing.JLabel();
        load = new javax.swing.JProgressBar();
        loadvalue = new javax.swing.JLabel();
        loadlabel = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        head.setFont(new java.awt.Font("MS Mincho", 1, 48)); // NOI18N
        head.setText("Pocket ");
        getContentPane().add(head, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, -1, 60));

        subhead.setFont(new java.awt.Font("MS Mincho", 1, 24)); // NOI18N
        subhead.setText("Hospital");
        getContentPane().add(subhead, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 140, -1, -1));
        getContentPane().add(load, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 410, 530, -1));

        loadvalue.setFont(new java.awt.Font("MS Mincho", 1, 12)); // NOI18N
        loadvalue.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(loadvalue, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 390, 40, 20));

        loadlabel.setFont(new java.awt.Font("MS Mincho", 1, 12)); // NOI18N
        loadlabel.setForeground(new java.awt.Color(255, 255, 255));
        loadlabel.setText("Loading.......");
        getContentPane().add(loadlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 390, 290, -1));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/loadingbg.jpg"))); // NOI18N
        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Loading.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Loading.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Loading.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Loading.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JLabel head;
    public javax.swing.JProgressBar load;
    public javax.swing.JLabel loadlabel;
    public javax.swing.JLabel loadvalue;
    private javax.swing.JLabel subhead;
    // End of variables declaration//GEN-END:variables
}
