/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pocket.hospital;

import java.awt.HeadlessException;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author aahir
 */
public class MedicineEntry extends javax.swing.JFrame {

    /**
     * Creates new form MedicineEntry
     */
    Connection conn = null;
    PreparedStatement pst = null;
    ResultSet rs = null;

    public MedicineEntry() {
        initComponents();
        conn = DbCon.ConnecrDb();
        updateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        x = new javax.swing.JLabel();
        heading = new javax.swing.JLabel();
        no = new javax.swing.JLabel();
        Medicine = new javax.swing.JLabel();
        Dose = new javax.swing.JLabel();
        no_entry = new javax.swing.JTextField();
        medicine_entry = new javax.swing.JTextField();
        dose_entry = new javax.swing.JTextField();
        insert_btn = new javax.swing.JButton();
        update_btn = new javax.swing.JButton();
        search_btn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        illness = new javax.swing.JComboBox<>();
        delete_btn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        med_table = new javax.swing.JTable();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        x.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/X.png"))); // NOI18N
        x.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                xMouseClicked(evt);
            }
        });
        jPanel1.add(x, new org.netbeans.lib.awtextra.AbsoluteConstraints(714, 10, -1, 30));

        heading.setFont(new java.awt.Font("MS Mincho", 1, 24)); // NOI18N
        heading.setText("Medicine Entry Portal");
        jPanel1.add(heading, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, 270, 40));

        no.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        no.setText("SI No");
        jPanel1.add(no, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 90, 30));

        Medicine.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        Medicine.setText("Medicine");
        jPanel1.add(Medicine, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 70, 30));

        Dose.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        Dose.setText("Dose");
        jPanel1.add(Dose, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 70, 30));
        jPanel1.add(no_entry, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 50, 30));
        jPanel1.add(medicine_entry, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 180, 30));
        jPanel1.add(dose_entry, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 180, 30));

        insert_btn.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        insert_btn.setText("INSERT");
        insert_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insert_btnActionPerformed(evt);
            }
        });
        jPanel1.add(insert_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 110, 30));

        update_btn.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        update_btn.setText("UPDATE");
        update_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_btnActionPerformed(evt);
            }
        });
        jPanel1.add(update_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 330, 110, 30));

        search_btn.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        search_btn.setText("SEARCH");
        search_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_btnActionPerformed(evt);
            }
        });
        jPanel1.add(search_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 120, 30));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel1.setText("Label");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 80, 30));

        illness.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        illness.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fever", "Cough", "Body-Pain", "Headache", "Stomache", "Cut", "Burn", "Vitamins", "Calcium" }));
        jPanel1.add(illness, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, 180, 30));

        delete_btn.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        delete_btn.setText("DELETE");
        delete_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_btnActionPerformed(evt);
            }
        });
        jPanel1.add(delete_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 330, 110, 30));

        med_table.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        med_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "MEDICINE", "DOSE", "LABEL"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        med_table.setRowSelectionAllowed(false);
        jScrollPane1.setViewportView(med_table);
        if (med_table.getColumnModel().getColumnCount() > 0) {
            med_table.getColumnModel().getColumn(0).setResizable(false);
            med_table.getColumnModel().getColumn(1).setResizable(false);
            med_table.getColumnModel().getColumn(2).setResizable(false);
            med_table.getColumnModel().getColumn(3).setResizable(false);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 80, 360, 280));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/panelbg.jpg"))); // NOI18N
        jPanel1.add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 454));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 741, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void updateTable(){
        String sql = "Select * from medicine";
        try{
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            med_table.setModel(DbUtils.resultSetToTableModel(rs));
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
          
    
    private void update_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_btnActionPerformed

        try {

            String id = no_entry.getText();
            String medicine = medicine_entry.getText();
            String dose = dose_entry.getText();
            String label = (String) illness.getSelectedItem();
            pst = conn.prepareStatement("UPDATE medicine set MEDICINE=?, DOSE=?, LABEL=? where ID=?");

            pst.setString(1, medicine);
            pst.setString(2, dose);
            pst.setString(3, label);
            pst.setString(4, id);
            pst.executeUpdate();

            JOptionPane.showMessageDialog(this, "Data updated successfully");

            no_entry.setText("");
            medicine_entry.setText("");
            dose_entry.setText("");

        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
        updateTable();
    }//GEN-LAST:event_update_btnActionPerformed

    private void search_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_btnActionPerformed

        try {
            pst = conn.prepareStatement("Select ID,MEDICINE,DOSE,LABEL from medicine where ID=?");
            int id = Integer.parseInt(no_entry.getText());
            pst.setInt(1, id);
            rs = pst.executeQuery();
            if (rs.next() == false) {
                JOptionPane.showMessageDialog(this, "Data Not Found");
                no_entry.setText("");
                medicine_entry.setText("");
                dose_entry.setText("");
            } else {
                no_entry.setText(rs.getString("id"));
                medicine_entry.setText(rs.getString("medicine"));
                dose_entry.setText(rs.getString("dose"));
                }

        } catch (HeadlessException | NumberFormatException | SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }

    }//GEN-LAST:event_search_btnActionPerformed

    private void insert_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insert_btnActionPerformed

        try {

            String medicine = medicine_entry.getText();
            String dose = dose_entry.getText();
            String label = (String) illness.getSelectedItem();
            pst = conn.prepareStatement("INSERT into medicine(MEDICINE,DOSE,LABEL) values(?,?,?)");
            pst.setString(1, medicine);
            pst.setString(2, dose);
            pst.setString(3, label);
            pst.executeUpdate();

            JOptionPane.showMessageDialog(null, "Data inserted successfully");

            no_entry.setText("");
            medicine_entry.setText("");
            dose_entry.setText("");
        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
        updateTable();
    }//GEN-LAST:event_insert_btnActionPerformed

    private void xMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_xMouseClicked
        
        int a = JOptionPane.showConfirmDialog(null, "Do you really want to go back", "Select", JOptionPane.YES_NO_OPTION);
        if(a== 0){
            new AdminHome().setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_xMouseClicked

    private void delete_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_btnActionPerformed

        try {

            String id = no_entry.getText();
            pst = conn.prepareStatement("DELETE from medicine where ID=?");
            pst.setString(1, id);
            pst.executeUpdate();

            JOptionPane.showMessageDialog(this, "Data deleted successfully");
            no_entry.setText("");
            medicine_entry.setText("");
            dose_entry.setText("");

        } 
        catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_delete_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MedicineEntry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MedicineEntry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MedicineEntry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MedicineEntry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new MedicineEntry().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Dose;
    private javax.swing.JLabel Medicine;
    private javax.swing.JLabel bg;
    private javax.swing.JButton delete_btn;
    private javax.swing.JTextField dose_entry;
    private javax.swing.JLabel heading;
    private javax.swing.JComboBox<String> illness;
    private javax.swing.JButton insert_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable med_table;
    private javax.swing.JTextField medicine_entry;
    private javax.swing.JLabel no;
    private javax.swing.JTextField no_entry;
    private javax.swing.JButton search_btn;
    private javax.swing.JButton update_btn;
    private javax.swing.JLabel x;
    // End of variables declaration//GEN-END:variables
}
